"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory$git_branch$git_status\
$aws$bun$c$cpp$cmake$deno$docker_context$gradle$java$kotlin$nix_shell$nodejs$ruby$rust
$username$os$hostname $character
"""

right_format = """
$cmd_duration
"""

palette = "midnight_cat"

[palettes.midnight_cat]
bg = "#25252d"
fg = "#e6e9ef"
blue = "#89b4fa"
purple = "#c4b5fd"
green = "#8bd5a0"
orange = "#f5a97f"
red = "#f38ba8"
cyan = "#94e2d5"
gray = "#7b8092"
yellow = "#f0e79c"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
style = "yellow bold"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "blue bold"

[git_commit]
tag_symbol = '  '

[git_status]
style = "red"

[username]
style_root = "bold red"
style_user = "bold cyan"
show_always = true

[os]
disabled = false

[hostname]
format = '[$ssh_symbol](bold blue)[$hostname](bold purple)'
ssh_only = false
ssh_symbol = " "

[cmd_duration]
format = '\[took [$duration]($style) \]'

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
